name: CI Download VNCovid19 Infographic
  
on:

  schedule:
    - cron: '0/10 * * * *'

  push:
    branches:
      - master
jobs:
  JsonUpgrades:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get countries Json
        run: |
          python downloadInfographic.py
          git config --global user.name 'trungmc'
          git config --global user.email 'trungmc@yahoo.com'
          git add .
          git commit --allow-empty -am "Update countries data"
          git push
          git status     
